title: <p align="center"> Vinayak SG</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/yesgvinayak">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & GenAI related problems.
  Working in on different projects for the past 5 years.
  <br>
  </p>



theme: jekyll-theme-minimal